[package]
name = "tauri_react_bar"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2024"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.4.1", features = [] }

[dependencies]
tauri = { version = "2.8.5", features = [] }
tauri-plugin-log = "2"
tauri-plugin-opener = "2.5.0"
log = "0.4.28"
xbar_core = { git = "https://github.com/beamiter/xbar_core.git", rev = "f0912c8d981af251e56b0a18a3432090fd6ba6ad", default-features = false, features = ["logging-flexi"] }
xbar_tauri = { git = "https://github.com/beamiter/xbar_core.git", rev = "f0912c8d981af251e56b0a18a3432090fd6ba6ad", features = ["clock-chrono", "provider-alsa", "provider-battery-sysfs", "provider-brightnessctl", "provider-system"] }
