[package]
name = "iced_bar"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", branch = "master", features = ["advanced", "debug", "lazy", "smol"] }
log = "0.4.33"
xbar_core = { path = "../../crates/xbar_core", default-features = false, features = ["clock-chrono", "config-toml", "glass", "logging-flexi", "provider-alsa", "provider-battery-sysfs", "provider-brightnessctl", "provider-network-sysfs", "provider-system", "transport-shared"] }
xbar_linux_actions = { path = "../../crates/xbar_core/crates/xbar_linux_actions" }
anyhow = "1.0.102"
futures-lite = "2"
raw-window-handle = "0.6"
wgpu = "29"
x11rb = { version = "0.13", features = ["allow-unsafe-code", "dl-libxcb"] }
