[package]
name = "winit_wgpu_bar"
version = "0.1.0"
edition = "2024"

[dependencies]
pollster = "1.0.1"
wgpu = "30.0.0"
anyhow = "1.0.103"
libc = "0.2.186"
log = "0.4.33"
xbar_core = { git = "https://github.com/beamiter/xbar_core.git" }
shared_structures = { git = "https://github.com/beamiter/shared_structures.git", features = ["use-futex"] }
winit = "0.30.13"
raw-window-handle = "0.6.2"
