[package]
name = "gpui_component_bar"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
chrono = "0.4"
futures = "0.3"
gpui = "0.2.2"
gpui-component = "0.5.1"
log = "0.4"
shared_structures = { git = "https://github.com/beamiter/shared_structures.git", features = ["use-futex"] }
xbar_core = { git = "https://github.com/beamiter/xbar_core.git" }
