//! Support-bundle schema compatibility tests.
//!
//! `jwm-support` emits a versioned JSON document that users attach to public
//! issues. These tests freeze the version-1 contract in two directions:
//!
//! 1. A bundle generated by the current binary must still satisfy the recorded
//!    version-1 requirements (no accidental field renames or type changes).
//! 2. The recorded fixture in `tests/fixtures/support_bundle_v1.json` must
//!    keep satisfying the same checker, so the requirements themselves cannot
//!    silently drift away from what version 1 promised.
//!
//! The generated bundle is also checked against the documented privacy
//! guarantees using sentinel values planted in the child environment.

use serde_json::Value;
use std::path::PathBuf;
use std::process::Command;

const SESSION_ENV_ALLOWLIST: &[&str] = &[
    "DISPLAY",
    "WAYLAND_DISPLAY",
    "XDG_SESSION_TYPE",
    "XDG_CURRENT_DESKTOP",
    "XDG_SESSION_DESKTOP",
    "DESKTOP_SESSION",
];

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("support_bundle_v1.json")
}

fn generate_offline_bundle(extra_env: &[(&str, &str)]) -> String {
    let mut command = Command::new(env!("CARGO_BIN_EXE_jwm-support"));
    command.args(["--offline", "--compact", "--backend", "x11rb"]);
    for (key, value) in extra_env {
        command.env(key, value);
    }
    let output = command.output().expect("run jwm-support");
    assert!(
        output.status.success(),
        "jwm-support failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).expect("bundle output is UTF-8")
}

fn required_str<'a>(value: &'a Value, pointer: &str) -> &'a str {
    value
        .pointer(pointer)
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("bundle field {pointer} must be a string"))
}

fn required_u64(value: &Value, pointer: &str) -> u64 {
    value
        .pointer(pointer)
        .and_then(Value::as_u64)
        .unwrap_or_else(|| panic!("bundle field {pointer} must be an unsigned integer"))
}

fn required_object<'a>(value: &'a Value, pointer: &str) -> &'a serde_json::Map<String, Value> {
    value
        .pointer(pointer)
        .and_then(Value::as_object)
        .unwrap_or_else(|| panic!("bundle field {pointer} must be an object"))
}

/// The frozen version-1 support-bundle contract.
///
/// Additive fields are allowed; every requirement asserted here is one that
/// existing consumers of version 1 may already rely on.
fn assert_support_bundle_v1(bundle: &Value) {
    assert_eq!(
        required_u64(bundle, "/schema_version"),
        1,
        "top-level schema_version must stay 1 until a versioned migration"
    );
    assert!(!required_str(bundle, "/generated_at").is_empty());
    assert_eq!(required_str(bundle, "/generator/name"), "jwm-support");
    assert!(!required_str(bundle, "/generator/version").is_empty());
    assert!(!required_str(bundle, "/requested_backend").is_empty());

    assert!(!required_str(bundle, "/system/os").is_empty());
    assert!(!required_str(bundle, "/system/architecture").is_empty());
    assert!(!required_str(bundle, "/system/family").is_empty());
    required_object(bundle, "/system/distribution");

    let session_environment = required_object(bundle, "/session_environment");
    for (key, value) in session_environment {
        assert!(
            SESSION_ENV_ALLOWLIST.contains(&key.as_str()),
            "session_environment key {key:?} is outside the documented allowlist"
        );
        assert!(value.is_string(), "session_environment value for {key:?}");
    }

    let doctor_status = required_str(bundle, "/doctor/status");
    assert!(
        ["pass", "warning", "error"].contains(&doctor_status),
        "unknown doctor status {doctor_status:?}"
    );
    assert!(required_u64(bundle, "/doctor/schema_version") >= 1);
    assert!(!required_str(bundle, "/doctor/backend").is_empty());
    required_u64(bundle, "/doctor/summary/passed");
    required_u64(bundle, "/doctor/summary/warnings");
    required_u64(bundle, "/doctor/summary/errors");
    assert_eq!(
        bundle.pointer("/doctor/config_diagnostics_included"),
        Some(&Value::Bool(false)),
        "support bundles must never embed raw configuration diagnostics"
    );
    let checks = bundle
        .pointer("/doctor/checks")
        .and_then(Value::as_array)
        .expect("doctor.checks must be an array");
    assert!(!checks.is_empty(), "doctor must report at least one check");
    for check in checks {
        let id = check
            .get("id")
            .and_then(Value::as_str)
            .expect("check id must be a string");
        assert!(!id.is_empty());
        let status = check
            .get("status")
            .and_then(Value::as_str)
            .expect("check status must be a string");
        assert!(["pass", "warning", "error"].contains(&status));
        assert!(check.get("summary").is_some_and(Value::is_string));
    }

    assert!(!required_str(bundle, "/privacy/environment_policy").is_empty());
    let omitted = bundle
        .pointer("/privacy/omitted_categories")
        .and_then(Value::as_array)
        .expect("privacy.omitted_categories must be an array");
    assert!(!omitted.is_empty());
    assert!(omitted.iter().all(Value::is_string));
}

#[test]
fn generated_offline_bundle_satisfies_the_v1_contract() {
    let raw = generate_offline_bundle(&[]);
    let bundle: Value = serde_json::from_str(&raw).expect("bundle is valid JSON");
    assert_support_bundle_v1(&bundle);
    assert!(
        bundle.get("live").is_none(),
        "offline bundles must not contain a live section"
    );
    assert_eq!(required_str(&bundle, "/requested_backend"), "x11rb");
}

#[test]
fn recorded_v1_fixture_still_satisfies_the_v1_contract() {
    let raw = std::fs::read_to_string(fixture_path()).expect("read recorded fixture");
    let bundle: Value = serde_json::from_str(&raw).expect("fixture is valid JSON");
    assert_support_bundle_v1(&bundle);
    assert!(bundle.get("live").is_none());
}

#[test]
fn generated_bundle_honors_the_documented_privacy_guarantees() {
    let home_sentinel = "/tmp/jwm-support-schema-home-sentinel";
    let dbus_sentinel = "unix:path=/tmp/jwm-support-dbus-sentinel";
    let secret_sentinel = "jwm-support-secret-sentinel-value";
    let path_sentinel = "/jwm-support-path-sentinel";
    let inherited_path = std::env::var("PATH").unwrap_or_default();

    let raw = generate_offline_bundle(&[
        ("HOME", home_sentinel),
        ("XDG_RUNTIME_DIR", home_sentinel),
        ("DBUS_SESSION_BUS_ADDRESS", dbus_sentinel),
        ("JWM_SUPPORT_TEST_SECRET", secret_sentinel),
        ("PATH", &format!("{inherited_path}:{path_sentinel}")),
    ]);

    // The bundle must parse and satisfy the schema even in a degraded
    // environment; privacy redaction must not depend on healthy checks.
    let bundle: Value = serde_json::from_str(&raw).expect("bundle is valid JSON");
    assert_support_bundle_v1(&bundle);

    for sentinel in [home_sentinel, dbus_sentinel, secret_sentinel, path_sentinel] {
        assert!(
            !raw.contains(sentinel),
            "support bundle leaked sentinel value {sentinel:?}"
        );
    }
}
