[package]
name = "gtk_bar"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
xbar_core = { path = "../../crates/xbar_core", default-features = false, features = ["clock-chrono", "logging-flexi", "provider-alsa", "provider-network-sysfs", "provider-system", "transport-shared"] }
xbar_linux_actions = { path = "../../crates/xbar_core/crates/xbar_linux_actions" }
gtk4 = { version = "0.11.4", features = ["v4_14"] }
gdk4 = { version = "0.11.4", features = ["v4_14"] }
