[package]
name = "relm_bar"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.33"
relm4 = { version = "0.11.0", features = ["libadwaita"] }
xbar_core = { path = "../../crates/xbar_core", default-features = false, features = ["clock-chrono", "logging-flexi", "provider-alsa", "provider-network-sysfs", "provider-system", "transport-shared"] }
xbar_linux_actions = { path = "../../crates/xbar_core/crates/xbar_linux_actions" }
