[package]
name = "gpui_component_bar"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
gpui = "0.2.2"
gpui-component = "0.5.1"
log = "0.4"
xbar_core = { path = "../../crates/xbar_core", default-features = false, features = ["clock-chrono", "logging-flexi", "provider-alsa", "provider-battery-sysfs", "provider-brightnessctl", "provider-network-sysfs", "provider-system", "transport-shared"] }
xbar_linux_actions = { path = "../../crates/xbar_core/crates/xbar_linux_actions" }
